
include $(GOROOT)/src/Make.inc

TARG=closure/template/soyutil
GOFILES=\
        bidi.go\
        const.go\
        data.go\
        sanitized_content.go\
        sanitizers.go\
        utils.go

DIRS=\

include $(GOROOT)/src/Make.pkg
